#url: http://localhost:4000
#baseurl: /
blogUrl: http://community.beck.de/category/legal-tech

# Site settings
title: Legal Tech Center
email: info@legaltech.center
description: "Am Legal Tech Center arbeiten Wissenschaftler, Anwälte, Unternehmer und Programmierer an digitalen Technologien und technologiegestützten Methoden im Recht"


# Team names, titles and social links
people:
- name: Stephan Breidenbach
  pic: sb
  position: Mitgründer und Leiter
  social:
    - title: envelope-o
      url: mailto:stephan.breidenbach@legaltech.center
    - title: twitter
      url: https://twitter.com/stebreidenbach

- name: Florian Glatz
  pic: fg
  position: Mitgründer und Leiter
  social:
    - title: envelope-o
      url: mailto:florian.glatz@legaltech.center
    - title: twitter
      url: https://twitter.com/heckerhut

- name: Paul von Bünau
  pic: pvb
  position: Fellow
  social:
    - title: envelope-o
      url: mailto:paul.von.buenau@legaltech.center


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - network:
    title: info@legaltech.center
    url: mailto:info@legaltech.center


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty